# Default values for fluvio.

loadBalancer:
  serviceAnnotations: {}
service:
  # type: ClusterIP
  type: NodePort
  # externalIps:
  #   - 192.168.0.151
  # externalName: test
scLog: info
tls: false
imagePullSecrets: []
image:
  registry: infinyon
  tag: "0.11.11"
  pullPolicy: IfNotPresent
cert:
  caCert: fluvio-ca
  tls: fluvio-tls
  domain: fluvio.local
authorizationConfigMap: ""
scPod:
  resources:
    requests:
      memory: 512Mi
    limits:
      memory: 512Mi
  nodeSelector: {}
  publicPort: 9003
  nodePort: 30003
  extraContainers: []
  extraEnv: []
  extraVolumes: []
  extraVolumeMounts: []
spuPod:
  resources:
    requests:
      memory: 256Mi
    limits:
      memory: 1Gi
  nodeSelector: {}
  storageClass: local-path
  baseNodePort: 30004
  extraContainers: []
  extraEnv: []
  extraVolumes: []
  extraVolumeMounts: []

rbac:
  create: true
serviceAccount:
  name: fluvio
podSecurityContext: {}